spring:
  redis:
    host: 8.130.114.255
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 360000
      cache-null-values: true
      key-prefix: Product_
      use-key-prefix: true
