server:
  port: 88
spring:
  cloud:
    gateway:
      routes:
        - id: member_route
          uri: lb://guli-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: ware_route
          uri: lb://guli-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: product_route
          uri: lb://guli-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third_party
          uri: lb://guli-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}

        - id: renren_admin
          uri: lb://renren-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-admin/$\{segment}

        - id: product_host_route
          uri: lb://guli-product
          predicates:
            - Host=guli.com

        - id: search_host_route
          uri: lb://guli-search
          predicates:
            - Host=search.guli.com
